apiVersion: v1
kind: Namespace
metadata:
  name: meubot
  labels:
    name: bot-telegram
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  namespace: meubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-telegram
  template:
    metadata:
      namespace: meubot
      labels:
        app: bot-telegram
    spec:
      containers:
      - name: bot
        image: quay.io/laurobmb/bot_python_telegram:latest
        imagePullPolicy: Always
        env:
         - name: NOMEBOT
           value: "Magali"
         - name: TOKEN
           value: "868879441:AAG-OV5QMFm9koeOdJmz1IisBE1v8HQ"
