frases_informatica:
  frase01:
    - "Fala pro cliente que "
    - "Com este commit, "
    - "Nesse pull request, "
    - "Dado o fluxo de dados atual, "
    - "Explica pro Product Onwer que "
    - "Desde ontem a noite "
    - "A equipe de suporte precisa saber que "
    - "A equipe do N1 precisa ver que "
    - "A equipe do N2 precisa ver que "
    - "A equipe do N3 precisa ver que "
    - "A equipe de arquitetos precisa ver que "
    - "A equipe de analistas precisa ver que "
    - "A equipe de tecnicos precisa ver que "
    - "O cliente tem que ver que "
    - "O cliente entende que "
    - "Fala para o cliente que "

  frase02:
    - "a normalização da data "
    - "um erro não identificado "
    - "o gerenciador de dependêancias do frontend "
    - "o módulo de recursção paralela "
    - "a otimização de performance da renderização do DOM "
    - "a disposição dos elementos HTML "
    - "a compilação final do programa "
    - "o deploy automatizado no WildFly "
    - "o faltimo pull request desse SCRUM "
    - "a TAG aplicada no sistema "

  frase03:
    - "deletou todas as entradas "
    - "otimizou a renderização "
    - "causou o bug "
    - "corrigiu o bug "
    - "superou o desempenho "
    - "complexificou o merge "
    - "facilitou a resolução de conflito "
    - "causou a race condition "
    - "facilitou o sintimento de utilização "

  frase04:
    - "do nosso servidor de DNS. "
    - "do nosso servidor WEB. "
    - "do polimorfismo aplicado nas classes. "
    - "do fluxo de dados de forma retroativa no server. "
    - "de estados esté1ticos nos componentes da UI. "
    - "do JSON compilado a partir de proto-buffers. "
    - "de uma compilação com tempo acima da media. "
    - "de uma configuração Webpack eficiente nos builds. "
    - "da execução parelela de funções em multi-threads. "
    - "de compilação multi-plataforma de forma asincrona. "
    - "da execução de requisições effcientes na API. "
    - "na estabilidade do protocolo de transferêancia de dados. "
    - "do carregamento de JSON delimitado por linhas. "
    - "na interpolação dinâmica de strings. "
    - "no parse retroativo do DOM. "
    - "no fechamento automático das tags. "
    - "na compilação de templates literais. "
    - "na definição de variaveis com tipos estéticos. "
    - "da renderização de floats parciais. "
    - "na organização alfanumérico dos arrays multidimensionais "
    - "dos parametros passados em funções privadas. "
    - "dos argumentos que definem um schema dinâmico. "
    - "na criação de novos polyfills para suportar os processos. "
